packageExtensions:
  "@pmndrs/handle@*":
    dependencies:
      three: "*"
  "@pmndrs/pointer-events@*":
    dependencies:
      three: "*"
  "@iwer/sem@*":
    dependencies:
      "@bufbuild/protobuf": "*"
  "@iwer/devui@*":
    dependencies:
      zustand: "*"
      
