services:
  webxr-workshop:
    stdin_open: true
    tty: true
    volumes:
      - source: vscode-server-extensions
        target: /home/dev/.vscode-server/extensions
        type: volume
      - source: vscode-server-insiders-extensions
        target: /home/dev/.vscode-server-insiders/extensions
        type: volume
      - source: yarn
        target: /home/dev/.yarn
        type: volume

volumes:
  vscode-server-extensions:
    name: webxr-workshop-vscode-server-extensions
  vscode-server-insiders-extensions:
    name: webxr-workshop-vscode-server-insiders-extensions
  yarn:
    name: webxr-workshop-yarn
