/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import type { FC } from "react";
import { useGLTF } from "@react-three/drei";
import { ModelComponentProps } from "../BoxScene";

type GLTFResult = ReturnType<typeof useGLTF> & {
  nodes: {
    Mesh_house_type03: THREE.Mesh;
    Mesh_house_type03_1: THREE.Mesh;
    Mesh_house_type03_2: THREE.Mesh;
    Mesh_house_type03_3: THREE.Mesh;
    Mesh_house_type03_4: THREE.Mesh;
  };
  materials: {
    ["border.003"]: THREE.MeshStandardMaterial;
    ["window.003"]: THREE.MeshStandardMaterial;
    ["door.003"]: THREE.MeshStandardMaterial;
    ["_defaultMat.003"]: THREE.MeshStandardMaterial;
    ["roof.005"]: THREE.MeshStandardMaterial;
  };
};

// type HouseProps = JSX.IntrinsicElements["group"] & Pick<THREE.Mesh, "scale">;
type HouseProps = ModelComponentProps;

export const House: FC<HouseProps> = (props) => {
  // const group = useRef<THREE.Group>(null);
  const { nodes, materials } = useGLTF(
    "https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/house-3/model.gltf"
  ) as GLTFResult;
  // props.ref = group;
  return (
    <group
      // ref={group}
      {...props}
      dispose={null}
      castShadow
      scale={props.scale}
      position={props.position}
    >
      <mesh
        castShadow
        geometry={nodes.Mesh_house_type03.geometry}
        material={materials["border.003"]}
      />
      <mesh
        castShadow
        geometry={nodes.Mesh_house_type03_1.geometry}
        material={materials["window.003"]}
      />
      <mesh
        castShadow
        geometry={nodes.Mesh_house_type03_2.geometry}
        material={materials["door.003"]}
      />
      <mesh
        castShadow
        geometry={nodes.Mesh_house_type03_3.geometry}
        material={materials["_defaultMat.003"]}
      />
      <mesh
        castShadow
        geometry={nodes.Mesh_house_type03_4.geometry}
        material={materials["roof.005"]}
      />
    </group>
  );
};

useGLTF.preload(
  "https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/house-3/model.gltf"
);
