/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { useEffect, useRef } from "react";
import type { JSX } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

type GLTFResult = ReturnType<typeof useGLTF> & {
  nodes: {
    Chapeau: THREE.SkinnedMesh;
    root: THREE.Bone;
  };
  materials: {
    ["color_main.014"]: THREE.MeshStandardMaterial;
  };
};

type ActionName = "course_chapeau" | "pose_chapeau";
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

export const Corrigan = (props: JSX.IntrinsicElements["group"]) => {
  const group = useRef<THREE.Group>(null);
  // @ts-expect-error animations is to be done later
  const { nodes, materials, animations } = useGLTF(
    "https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/korrigan-hat/model.gltf"
  ) as GLTFResult;
  // @ts-expect-error this is to be done later
  const { actions } = useAnimations<GLTFActions>(animations, group);

  useEffect(() => {
    // @ts-expect-error related to animation type issues
    actions["pose_chapeau"].play();
  }, []);

  return (
    <group
      ref={group}
      {...props}
      dispose={null}
    >
      <group
        rotation={[0, 0.01, 0]}
        scale={5}
      >
        <primitive object={nodes.root} />
        <skinnedMesh
          // animations={animations}
          geometry={nodes.Chapeau.geometry}
          material={materials["color_main.014"]}
          skeleton={nodes.Chapeau.skeleton}
        />
      </group>
    </group>
  );
};

useGLTF.preload(
  "https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/korrigan-hat/model.gltf"
);
